# Generated by Django 3.0.3 on 2020-02-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player1', models.CharField(max_length=200)),
                ('player2', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Problems')),
            ],
        ),
    ]
