# Generated by Django 3.0.3 on 2020-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
